DELIMITER $$

DROP PROCEDURE IF EXISTS `PR_MOD_COL`$$

CREATE  PROCEDURE `PR_MOD_COL`(
MOD_TABLE_NAME VARCHAR(50),
MOD_TYPE VARCHAR(10),
MOD_COLUMN_NAME VARCHAR(50),
COL_TYPE VARCHAR(20),
COL_DEFAULT VARCHAR(50),
COL_IS_NULLABLE VARCHAR(30),
COL_COMMENT VARCHAR(200)
)
BEGIN
		/*MOD_TABLE_NAME:the table you want to modify*/
    /*MOD_TYPE in ('add','drop','modify'): 'add' means add column,'drop' means drop column,'modify' means mod column*/
    /*MOD_COLUMN_NAME:the column you want to modify*/
    /*COL_TYPE in ('INT','VARCHAR(200)','DATETIME',....) column datatype*/
    /*COL_DEFAULT column default value*/
    /*COL_IS_NULLABLE in ('NULL','NOT NULL') column attribute*/   
    /*COL_COMMENT column comment must be in english*/
		DECLARE TAB_CNT INT DEFAULT -1;
    DECLARE COL_CNT INT DEFAULT -1;
		DECLARE V_SQL VARCHAR(500) DEFAULT '';
		DECLARE V_SQL_DEF VARCHAR(500) DEFAULT '';
		DECLARE V_SQL_COMM VARCHAR(500) DEFAULT '';
		DECLARE COL_DATA_TYPE VARCHAR(20) DEFAULT '';
		DECLARE ERR_ID INT DEFAULT 0;
	  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET ERR_ID = 104; 
		SELECT COUNT(1)  INTO TAB_CNT 
    FROM INFORMATION_SCHEMA.TABLES  
    WHERE UPPER(TABLE_SCHEMA) = UPPER(DATABASE()) 
      AND UPPER(TABLE_NAME) = UPPER(REPLACE(MOD_TABLE_NAME,' ','')) ;
    SELECT COUNT(1)  INTO COL_CNT 
    FROM INFORMATION_SCHEMA.COLUMNS  
    WHERE UPPER(TABLE_SCHEMA) = UPPER(DATABASE()) 
      AND UPPER(TABLE_NAME) = UPPER(REPLACE(MOD_TABLE_NAME,' ','')) 
      AND UPPER(COLUMN_NAME) = UPPER(REPLACE(MOD_COLUMN_NAME,' ',''));
		IF REPLACE(UPPER(MOD_TYPE),' ','') = 'DROP' THEN
		    IF COL_CNT > 0 THEN
            SET V_SQL = MOD_COLUMN_NAME ;
        END IF;
		ELSEIF REPLACE(UPPER(MOD_TYPE),' ','') = 'ADD' THEN
		    IF TAB_CNT > 0 AND COL_CNT = 0 THEN
            SET V_SQL = CONCAT(MOD_COLUMN_NAME,' ',COL_TYPE,' ',COL_IS_NULLABLE);
        END IF;
		ELSEIF REPLACE(UPPER(MOD_TYPE),' ','') = 'MODIFY' THEN
		    IF COL_CNT > 0 THEN
            SET V_SQL = CONCAT(MOD_COLUMN_NAME,' ',COL_TYPE,' ',COL_IS_NULLABLE);
        END IF;
		ELSE
       SET V_SQL = ' () '; 
		END IF;
		IF V_SQL <> '' THEN
	      SET V_SQL = CONCAT('ALTER TABLE ', MOD_TABLE_NAME,' ',MOD_TYPE,' COLUMN ',V_SQL);
        SET @V_SQL=V_SQL;  
        PREPARE STMT FROM @V_SQL;
        EXECUTE STMT;      
        DEALLOCATE PREPARE STMT;             
    END IF;
		IF (REPLACE(UPPER(MOD_TYPE),' ','') = 'ADD' OR REPLACE(UPPER(MOD_TYPE),' ','') = 'MODIFY') AND REPLACE(COL_COMMENT,' ','') <> '' THEN
		    SET V_SQL_COMM = CONCAT('ALTER TABLE ' ,MOD_TABLE_NAME,' MODIFY COLUMN ',MOD_COLUMN_NAME,' ',COL_TYPE,' COMMENT ','\'',COL_COMMENT,'\'');
				SET @V_SQL_COMM=V_SQL_COMM;  
				PREPARE STMT FROM @V_SQL_COMM;
				EXECUTE STMT;      
				DEALLOCATE PREPARE STMT;
		END IF;
		IF (REPLACE(UPPER(MOD_TYPE),' ','') = 'ADD' OR REPLACE(UPPER(MOD_TYPE),' ','') = 'MODIFY') AND  COL_DEFAULT <> '' THEN
	      IF REPLACE(UPPER(COL_DEFAULT),' ','') = 'NULL' OR REPLACE(UPPER(COL_DEFAULT),' ','')='CURRENT_TIMESTAMP' THEN 
				    SET V_SQL_DEF = COL_DEFAULT;
				ELSE
						SELECT DATA_TYPE  INTO COL_DATA_TYPE 
						FROM INFORMATION_SCHEMA.COLUMNS  
						WHERE UPPER(TABLE_SCHEMA) = UPPER(DATABASE()) 
							AND UPPER(TABLE_NAME) = UPPER(REPLACE(MOD_TABLE_NAME,' ','')) 
							AND UPPER(COLUMN_NAME) = UPPER(REPLACE(MOD_COLUMN_NAME,' ',''));
						IF UPPER(COL_DATA_TYPE) = 'TINYINT' OR UPPER(COL_DATA_TYPE) = 'SMALLINT' OR UPPER(COL_DATA_TYPE) = 'MEDIUMINT' OR 
							 UPPER(COL_DATA_TYPE) = 'INT' OR UPPER(COL_DATA_TYPE) = 'INTEGER' OR UPPER(COL_DATA_TYPE) = 'INTEGER' OR 
							 UPPER(COL_DATA_TYPE) = 'BIGINT' OR UPPER(COL_DATA_TYPE) = 'FLOAT' OR UPPER(COL_DATA_TYPE) = 'DOUBLE' OR 
							 UPPER(COL_DATA_TYPE) = 'REAL' OR UPPER(COL_DATA_TYPE) = 'DECIMAL' OR UPPER(COL_DATA_TYPE) = 'NUMERIC'  THEN
								SET V_SQL_DEF = COL_DEFAULT;
						ELSEIF UPPER(COL_DATA_TYPE) = 'CHAR' OR UPPER(COL_DATA_TYPE) = 'VARCHAR'  OR UPPER(COL_DATA_TYPE) = 'TINYBLOB' OR 
									 UPPER(COL_DATA_TYPE) = 'TINYTEXT' OR UPPER(COL_DATA_TYPE) = 'BLOB' OR UPPER(COL_DATA_TYPE) = 'TEXT'  OR 
									 UPPER(COL_DATA_TYPE) = 'MEDIUMBLOB' OR UPPER(COL_DATA_TYPE) = 'MEDIUMTEXT' OR UPPER(COL_DATA_TYPE) = 'LONGBLOB' OR 
									 UPPER(COL_DATA_TYPE) = 'LONGTEXT' OR UPPER(COL_DATA_TYPE) = 'DATETIME' OR  UPPER(COL_DATA_TYPE) = 'TIMESTAMP'  THEN
								SET V_SQL_DEF = CONCAT('\'',COL_DEFAULT,'\'');
						END IF;			  	
        END IF;
        SET V_SQL_DEF = CONCAT('ALTER TABLE ', MOD_TABLE_NAME,' ALTER COLUMN ',MOD_COLUMN_NAME,' SET DEFAULT ',V_SQL_DEF);
				SET @V_SQL_DEF=V_SQL_DEF;  
				PREPARE STMT FROM @V_SQL_DEF;
				EXECUTE STMT;      
				DEALLOCATE PREPARE STMT;				
    END IF;
		SELECT CONCAT('SUCCESS: ',V_SQL,'; ',V_SQL_COMM,'; ',V_SQL_DEF);
END$$

DELIMITER ;